# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  # first cron
  - name: hello-world
    image:
      repository: hello-world
      tag: latest
      imagePullPolicy: IfNotPresent
    schedule: "* * * * *"
    restartPolicy: OnFailure
  # second cron