
{{- $release_name := .Release.Name }}
{{- range $job := .Values.jobs }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $job.appSecret.secretName }}
  labels:
    app: "{{ $release_name }}-{{ $job.name }}"
type: "Opaque"
data:
  _VAULT_RINGMASTER: {{ $job.appSecret.useVault | b64enc | quote }}
  _VAULT_RINGMASTER_VAULT_ADDR: {{ $job.appSecret.vaultAddr | b64enc | quote }}
  _VAULT_RINGMASTER_SECRET_PATH: {{ $job.appSecret.vaultSecretPath | b64enc | quote }}
  _VAULT_RINGMASTER_SECRET_VERSION: {{ $job.appSecret.vaultSecretVersion | b64enc | quote }}
  _VAULT_RINGMASTER_USERNAME: {{ $job.appSecret.keycloakUsername | b64enc | quote }}
  _VAULT_RINGMASTER_PASSWORD: {{ $job.appSecret.keycloakPassword | b64enc | quote }}
  _VAULT_RINGMASTER_TOKEN_URL: {{ $job.appSecret.keycloakTokenUrl | b64enc | quote }}
  _VAULT_RINGMASTER_CLIENT_ID: {{ $job.appSecret.keycloakClientId | b64enc | quote }}
  _VAULT_RINGMASTER_CLIENT_SECRET: {{ $job.appSecret.keycloakClientSecret | b64enc | quote }}

{{- end }}